services:
  db:
    image: postgres:17.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres-teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      